version: 2
jobs:
  build:
    only:
      - staging
    working_directory: ~/project
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: install hasura cli
          command: |
            curl -L# -o /bin/hasura https://github.com/hasura/graphql-engine/releases/download/v1.0.0-beta.1/cli-hasura-linux-amd64
            chmod +x /bin/hasura


      - run:
          name: apply migrations
          command: |
            cd ../
            hasura migrate apply --endpoint "$HASURA_ENDPOINT" # --admin-secret "$HASURA_ADMIN_SECRET"

